CREATE TABLE REPRESENTANTE (
    `REP_ID` INT NOT NULL AUTO_INCREMENT,
    `REP_CI` VARCHAR(10) NOT NULL,
    `REP_NOM` VARCHAR(100) NOT NULL,
    `REP_NOM2` VARCHAR(100) NOT NULL,
    `REP_APE` VARCHAR(100) NOT NULL,
    `REP_APE2` VARCHAR(100) NOT NULL,
    `REP_DIR` VARCHAR(400) NOT NULL,
    `REP_CEL` VARCHAR(10) NOT NULL,
    `REP_TEL` VARCHAR(10) NOT NULL,
    `REP_MAIL` VARCHAR(100) NOT NULL,
    `REP_REL_FAM` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`REP_ID`)
) ENGINE = InnoDB;
CREATE TABLE ESTUDIANTE (
    `EST_ID` INT NOT NULL AUTO_INCREMENT,
    `EST_CI` VARCHAR(10) NOT NULL,
    `EST_NOM` VARCHAR(100) NOT NULL,
    `EST_NOM2` VARCHAR(100) NOT NULL,
    `EST_APE` VARCHAR(100) NOT NULL,
    `EST_APE2` VARCHAR(100) NOT NULL,
    `EST_FECH_NAC` DATE NOT NULL,
    `EST_GEN` CHAR(1) NOT NULL,
    `REP_ID` INT NOT NULL,
    PRIMARY KEY (`EST_ID`),
    FOREIGN KEY (`REP_ID`) REFERENCES `representante` (`REP_ID`)
) ENGINE = InnoDB;
CREATE TABLE PROFESOR (
    `PRF_ID` INT NOT NULL AUTO_INCREMENT,
    `PRF_CI` VARCHAR(10) NOT NULL,
    `PRF_NOM` VARCHAR(100) NOT NULL,
    `PRF_NOM2` VARCHAR(100) NOT NULL,
    `PRF_APE` VARCHAR(100) NOT NULL,
    `PRF_APE2` VARCHAR(100) NOT NULL,
    `PRF_FECH_NAC` DATE NOT NULL,
    `PRF_GEN` CHAR(1) NOT NULL,
    `PRF_DIR` VARCHAR(400) NOT NULL,
    `PRF_CEL` VARCHAR(10) NOT NULL,
    `PRF_TEL` VARCHAR(10) NOT NULL,
    `PRF_MAIL` VARCHAR(100) NOT NULL,
    `PRF_FECH_INGR_INST` DATE NOT NULL,
    `PRF_FECH_INGR_MAG` DATE NOT NULL,
    PRIMARY KEY (`PRF_ID`)
) ENGINE = InnoDB;
CREATE TABLE CURSO(
    `CRS_ID` INT NOT NULL AUTO_INCREMENT,
    `CRS_NOM` VARCHAR(100) NOT NULL,
    `CRS_NUM` INT NOT NULL,
    `CRS_ID_ANL` INT NOT NULL,
    PRIMARY KEY (`CRS_ID`)
) ENGINE = InnoDB;
CREATE TABLE PARALELO (
    `PRLL_ID` INT NOT NULL AUTO_INCREMENT,
    `PRLL_NOM` CHAR(1) NOT NULL,
    `CRS_ID` INT NOT NULL,
    `PRF_REP_ID` INT NOT NULL,
    PRIMARY KEY (`PRLL_ID`),
    FOREIGN KEY (`CRS_ID`) REFERENCES `curso` (`CRS_ID`),
    FOREIGN KEY (`PRF_REP_ID`) REFERENCES `Profesor` (`PRF_ID`)
) ENGINE = InnoDB;
CREATE TABLE ANIO_LECTIVO(
    `ANL_ID` INT NOT NULL AUTO_INCREMENT,
    `ANL_INI` DATE NOT NULL,
    `ANL_FIN` DATE NOT NULL,
    `ANL_NUM_PRD` INT NOT NULL,
    PRIMARY KEY (`ANL_ID`)
) ENGINE = InnoDB;
CREATE TABLE MATRICULA(
    `MTRC_ID` INT NOT NULL AUTO_INCREMENT,
    `ANL_ID` INT NOT NULL,
    `PRLL_ID` INT NOT NULL,
    `EST_ID` INT NOT NULL,
    `MTRC_STD` INT NOT NULL,
    PRIMARY KEY (`MTRC_ID`),
    FOREIGN KEY (`PRLL_ID`) REFERENCES `PARALELO` (`PRLL_ID`),
    FOREIGN KEY (`EST_ID`) REFERENCES `ESTUDIANTE` (`EST_ID`),
    FOREIGN KEY (`ANL_ID`) REFERENCES `ANIO_LECTIVO` (`ANL_ID`)
) ENGINE = InnoDB;
CREATE TABLE ASIGNATURA(
    `ASG_ID` INT NOT NULL AUTO_INCREMENT,
    `ASG_NOM` VARCHAR(100) NOT NULL,
    `ASG_TIP` INT NOT NULL,
    PRIMARY KEY (`ASG_ID`)
) ENGINE = InnoDB;
CREATE TABLE ASIGNATURA_CURSO(
    `ASG_CRS_ID` INT NOT NULL AUTO_INCREMENT,
    `ASG_ID` INT NOT NULL,
    `CRS_ID` INT NOT NULL,
    PRIMARY KEY (`ASG_CRS_ID`),
    FOREIGN KEY (`ASG_ID`) REFERENCES `ASIGNATURA` (`ASG_ID`),
    FOREIGN KEY (`CRS_ID`) REFERENCES `CURSO` (`CRS_ID`)
) ENGINE = InnoDB;
CREATE TABLE ASIGNATURA_PARALELO (
    `ASG_PRLL_ID` INT NOT NULL AUTO_INCREMENT,
    `ASG_CRS_ID` INT NOT NULL,
    `PRL_ID` INT NOT NULL,
    `PRF_ASG_ID` INT NOT NULL,
    PRIMARY KEY (`ASG_PRLL_ID`),
    FOREIGN KEY (`PRL_ID`) REFERENCES `PARALELO` (`PRLL_ID`),
    FOREIGN KEY (`PRF_ASG_ID`) REFERENCES `ASIGNATURA` (`ASG_ID`)
) ENGINE = InnoDB;

CREATE TABLE CALIFICACIONES(
    
) ENGINE = InnoDB;