export interface Profesor{
    PRF_ID:number
    PRF_DNI:string
    PRF_NOM:string
    PRF_NOM2:string
    PRF_APE:string
    PRF_APE2:string
    /*PRF_FECH_NAC
    PRF_GEN
    PRF_DIR
    PRF_CEL
    PRF_TEL
    PRF_MAIL
    PRF_FECH_INGR_INST
    PRF_FECH_INGR_MAG
    PRF_ESTADO
    USR_CREADOR_ID
    FECHA_CREACION*/
}