CREATE TABLE USUARIO (
    USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_DNI VARCHAR(10) NOT NULL,
    USR VARCHAR(10) NOT NULL,
    USR_PSWD VARCHAR(10) NOT NULL,
    USR_ESTADO CHAR(1) NOT NULL CHECK (USR_ESTADO IN ('A', 'I')),
    USR_TIPO CHAR(1) NOT NULL CHECK (USR_TIPO IN ('A', 'R', 'P')),
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (USR),
    UNIQUE (USR_DNI),
    PRIMARY KEY(USR_ID)
);
CREATE TABLE ANIO_LECTIVO (
    AL_ID INT NOT NULL AUTO_INCREMENT,
    AL_INI DATE NOT NULL,
    AL_FIN DATE NOT NULL,
    AL_PRD INT NOT NULL,
    AL_SUB_PRD INT NOT NULL,
    AL_ESTADO CHAR(1) NOT NULL CHECK (AL_ESTADO IN ('A', 'I')),
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (AL_INI),
    UNIQUE (AL_FIN),
    PRIMARY KEY(AL_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE CURSO(
    CRS_ID INT NOT NULL AUTO_INCREMENT,
    CRS_NOM INT NOT NULL,
    CRS_TIP VARCHAR(15) NOT NULL,
    CRS_ESTADO CHAR(1) NOT NULL CHECK (CRS_ESTADO IN ('A', 'I')),
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(CRS_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE REPRESENTANTE(
    REP_ID INT NOT NULL AUTO_INCREMENT,
    REP_DNI varchar(10) NOT NULL,
    REP_NOM varchar(100) NOT NULL,
    REP_NOM2 varchar(100) NOT NULL,
    REP_APE varchar(100) NOT NULL,
    REP_APE2 varchar(100) NOT NULL,
    REP_DIR varchar(400) NOT NULL,
    REP_CEL varchar(10) NOT NULL,
    REP_TEL varchar(10) NOT NULL,
    REP_MAIL varchar(100) NOT NULL,
    REP_REL_FAM varchar(100) NOT NULL,
    REP_ESTADO CHAR(1) NOT NULL CHECK (REP_ESTADO IN ('A', 'I')),
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (REP_DNI),
    PRIMARY KEY(REP_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE ESTUDIANTE (
    EST_ID INT NOT NULL AUTO_INCREMENT,
    EST_DNI varchar(10) NOT NULL,
    EST_NOM varchar(100) NOT NULL,
    EST_NOM2 varchar(100) NOT NULL,
    EST_APE varchar(100) NOT NULL,
    EST_APE2 varchar(100) NOT NULL,
    EST_FECH_NAC date NOT NULL,
    EST_GEN char(1) NOT NULL,
    EST_ESTADO CHAR(1) NOT NULL CHECK (EST_ESTADO IN ('A', 'I')),
    REP_ID INT NOT NULL,
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (EST_DNI),
    PRIMARY KEY(EST_ID),
    FOREIGN KEY (REP_ID) REFERENCES REPRESENTANTE (REP_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE ASIGNATURA (
    ASG_ID INT NOT NULL AUTO_INCREMENT,
    ASG_NOM varchar(100) NOT NULL,
    ASG_TIP CHAR(2) NOT NULL CHECK (ASG_TIP IN ('CU', 'CL')),
    ASG_ESTADO CHAR(1) NOT NULL CHECK (ASG_ESTADO IN ('A', 'I')),
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ASG_NOM),
    PRIMARY KEY(ASG_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE PROFESOR (
    PRF_ID INT NOT NULL AUTO_INCREMENT,
    PRF_DNI varchar(10) NOT NULL,
    PRF_NOM varchar(100) NOT NULL,
    PRF_NOM2 varchar(100) NOT NULL,
    PRF_APE varchar(100) NOT NULL,
    PRF_APE2 varchar(100) NOT NULL,
    PRF_FECH_NAC date NOT NULL,
    PRF_GEN char(1) NOT NULL,
    PRF_DIR varchar(400) NOT NULL,
    PRF_CEL varchar(10) NOT NULL,
    PRF_TEL varchar(10) NOT NULL,
    PRF_MAIL varchar(100) NOT NULL,
    PRF_FECH_INGR_INST date NOT NULL,
    PRF_FECH_INGR_MAG date NOT NULL,
    PRF_ESTADO CHAR(1) NOT NULL CHECK (PRF_ESTADO IN ('A', 'I')),
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (PRF_DNI),
    PRIMARY KEY(PRF_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE PARALELO(
    PRLL_ID INT NOT NULL AUTO_INCREMENT,
    PRLL_NOM VARCHAR(100) NOT NULL,
    PRLL_ESTADO CHAR(1) NOT NULL CHECK (PRLL_ESTADO IN ('A', 'I')),
    CRS_ID INT NOT NULL,
    PRF_ID INT NOT NULL,
    AL_ID INT NOT NULL,
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(CRS_ID,AL_ID),
    PRIMARY KEY(PRLL_ID),
    FOREIGN KEY (CRS_ID) REFERENCES CURSO (CRS_ID),
    FOREIGN KEY (PRF_ID) REFERENCES PROFESOR (PRF_ID),
    FOREIGN KEY (AL_ID) REFERENCES ANIO_LECTIVO (AL_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE MATRICULA(
    MTRC_ID INT NOT NULL AUTO_INCREMENT,
    MTRC_PASE CHAR(2) NOT NULL CHECK (MTRC_PASE IN ('A', 'R', 'EP')),
    MTRC_ESTADO CHAR(1) NOT NULL CHECK (MTRC_ESTADO IN ('A', 'I')),
    EST_ID INT NOT NULL,
    PRLL_ID INT NOT NULL,
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(MTRC_ID),
    FOREIGN KEY (EST_ID) REFERENCES ESTUDIANTE (EST_ID),
    FOREIGN KEY (PRLL_ID) REFERENCES PARALELO (PRLL_ID),
    FOREIGN KEY (USR_CREADOR_ID) REFERENCES USUARIO (USR_ID)
);
CREATE TABLE ASG_PRLL_PRF(
    ASG_PRLL_PRF_ID INT NOT NULL AUTO_INCREMENT,
    ASG_PRL_PRF_ESTADO CHAR(1) NOT NULL CHECK (ASG_PRL_PRF_ESTADO IN ('A', 'I')),
    ASG_ID INT NOT NULL,
    PRF_ID INT NOT NULL,
    PRLL_ID INT NOT NULL,
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ASG_PRLL_PRF_ID),
    FOREIGN KEY (ASG_ID) REFERENCES ASIGNATURA (ASG_ID),
    FOREIGN KEY (PRF_ID) REFERENCES PROFESOR (PRF_ID),
    FOREIGN KEY (PRLL_ID) REFERENCES PARALELO (PRLL_ID)
);
CREATE TABLE CALIFICACION(
    CLF_ID INT NOT NULL AUTO_INCREMENT,
    CLF_PRD VARCHAR(10) NOT NULL,
    CLF_SPRD VARCHAR(10) NOT NULL,
    CLF_NOTA FLOAT NOT NULL,
    CLF_ESTADO CHAR(1) NOT NULL CHECK (CLF_ESTADO IN ('A', 'I')),
    MTRC_ID INT NOT NULL,
    ASG_PRLL_PRF_ID INT NOT NULL,
    USR_CREADOR_ID INT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(CLF_ID),
    FOREIGN KEY (MTRC_ID) REFERENCES MATRICULA (MTRC_ID),
    FOREIGN KEY (ASG_PRLL_PRF_ID) REFERENCES ASG_PRLL_PRF (ASG_PRLL_PRF_ID)
);